### ISSUE TITLE
Making sure links to emails work properly 

### ISSUE THREAD

**Issue by gmims** [CS-451-Spring-2015/CCSC_Submission_System#12]
Make sure that contact emails work on all computers.

**Comment by Nyankuru** [comment]
I checked the contact emails and they are working fine. The "mailto" link is what is used on those emails which when clicked opens up the default email program on the computer. It's not possible to have the emails open up the same way on all computers because one computer might have Gmail and another might have a different email program like outlook. If there is no default email program, the user will get an error saying that "there is no email program associated to perform the action."

Non issue. Closing case.
